[workspace]
resolver = "2"
members = [
    "crates/vision-core",
    "crates/vision-detection",
    "crates/vision-nt",
]

[workspace.dependencies]
tracing = "0.1.44"
tracing-subscriber = { version = "0.3.22", features = ["env-filter"] }
ndarray = { version = "0.17.2", features = ["rayon"] }
