[system]
log_level = "info"
telemetry_enabled = true

[networktables]
server = "10.TE.AM.2"  # Robot IP
identity = "rusty-vision"
publish_rate_hz = 50

[camera]
device_id = 0
width = 1920
height = 1080
fps = 30

[detection]
enabled = true
color_lower = [20, 120, 140]  # HSV
color_upper = [75, 255, 255]
min_contour_length = 100
min_area = 100.0
min_radius = 40
max_radius = 400
radius_step = 4

# [web]
# enabled = true
# port = 5800
