[system]
log_level = "info"
telemetry_enabled = true

[networktables]
server = "10.TE.AM.2"  # Robot IP
identity = "rusty-vision"
publish_rate_hz = 50

[camera]
device_id = 1
width = 1280
height = 800
fps = 100

[detection]
color_lower = [10, 150, 115]  # HSV
color_upper = [130, 255, 255]
min_contour_length = 100
min_area = 100.0
min_radius = 40
max_radius = 400
radius_step = 4
vote_thresh = 15

[web]
port = 5800
